server:
  servlet:
    context-path: /
  port: 8081

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    name: simple-web-app
  flyway:
    baselineOnMigrate: true
    enabled: true
